name: Metrics
on:
  schedule: [{cron: "0 */4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: Haavertz
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, languages
          config_timezone: America/Sao_Paulo
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%


      - name: Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: media.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          config_order: anilist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_user: Havertz
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
