name: Metrics
on:
  schedule: [{cron: "0 */4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          config_order: anilist
          output_action: gist
          committer_gist: ${{ secrets.TOKEN }}
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
